#!/bin/bash
# Provide a simple math tutor for a second-grade student in an elementary school
# Repeatedly display the main menu to let the user choose an option (enter Q or q to quit):
#    if opiton is 1, generate an addition problem for the user to solve
#    if opiton is 2, generate a subtraction problem for the user to solve
#    if opiton is 3, generate a multiplication problem for the user to solve
#    if other option, display the message of invalid choice.
# For each option of 1, 2, or 3, it should wait for the user to enter the answer
#    if the answer is correct, a message of congratulations should be displayed
#    if the answer is wrong, the correct answer should be displayed

usr_option=a

while [ 1 -eq 1 ]
do

    echo "     Math Is Fun! Take a challenge..."
    echo "-------------------------------------"
    echo "1. Addition problem"
    echo "2. Subtraction problem"
    echo "3. Multiplication problem"
    echo "-------------------------------------"
    echo "Please input your menu option (enter Q or q to quit)"
    read usr_option

    case $usr_option in
        1) rnum1=$(((RANDOM % (50 - 1 + 1)) + 1))
           rnum2=$(((RANDOM % (50 - 1 + 1)) + 1))
           echo "$rnum1 + $rnum2 ="
           sum=$((rnum1+rnum2))
           read user_answer
           
           if [ $user_answer -eq $sum ]
           then echo "Congratulations! That is right."
           else
               echo "Sorry, the correct answer is $sum"
           fi;;
        
        2) rnum1=$(((RANDOM % (50 - 1 + 1)) + 1))
           rnum2=$(((RANDOM % (50 - 1 + 1)) + 1))
          
           if [ $rnum1 -lt  $rnum2 ]
           then temp=$((rnum1 + 0))
                rnum1=$((rnum2 + 0))
                rnum2=$((temp + 0))
           fi
           
           echo "$rnum1 - $rnum2 = "
           diff=$((rnum1-rnum2))
           read user_answer

           if [ $user_answer -eq $diff ]
           then echo "Congratulations! That is right."
           else
               echo "Sorry, the correct answer is $diff"
           fi;;
        
        3) rnum1=$(((RANDOM % (10 - 1 + 1)) + 1))
           rnum2=$(((RANDOM % (10 - 1 + 1)) + 1))
           echo "$rnum1 * $rnum2 = "
           prod=$((rnum1*rnum2))
           read user_answer

           if [ $user_answer -eq $prod ]
           then echo "Congratulations! That is right."
           else
               echo "Sorry, the correct answer is $prod"
           fi;;
        
        [Qq]) echo "Hope you enjoy solving Math problems, see you later..."
              exit;;
        
        *) echo "Your choice is not valid";;

        
   esac

done


# Your script should start here
# create a loop to repeatedly ask the user to input the option from the main menu until the user enters Q or q to quit
